image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

frontend:
  stage: build
  tags:
    - dalfcs_docker_autoscale
  script:
    - cd client
    - npm install
    - npm run build
  artifacts:
    paths:
      - client/dist/
  only:
    - master

backend:
  stage: build
  script:
    - cd backend
    - npm install
    - npm run build
  artifacts:
    paths:
      - backend/dist/
  only:
    - master

deploy:
  stage: deploy
  script:
    - apt-get update -yq
    - apt-get install -yq git
    - git config --global user.email "deploy@heroku.com"
    - git config --global user.name "Heroku Deploy"
    - git clone https://git.heroku.com/bidforgoodauction.git
    - cd bidforgoodauction
    - rm -rf *
    - cp -r ../client/dist/* .
    - cp -r ../backend/dist/* .
    - git add .
    - git commit -m "Deploy to Heroku"
    - git push heroku master
  only:
    - deployment






# image: node:latest
# stages:          # List of stages for jobs, and their order of execution
#   - build
#   - test

# build:       # This job runs in the build stage, which runs first.
#   stage: build
#   tags:
#   - dalfcs_docker_autoscale
#   script:
#   - cd ./server/
#   - npm install
#   - npm run build


# test:   # This job runs in the test stage.
#   stage: test    # It only starts when the job in the build stage completes successfully.
#   script:
#   - cd ./server/  
#   - npm run test