image: maven:latest
stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
  - dalfcs_docker_autoscale
  script:
  - mvn compile


test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
  - mvn test