image: node:18
stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
  - dalfcs_docker_autoscale
  script:
  - npm install
  - npm run build


test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
  - npm run test