
stages:
  - build
  - test
  - deploy

backend-build:
  stage: build
  tags:
    - dalfcs_docker_autoscale
  image: node:latest
  script:
    - ls
    - echo "Started building backend application."
    - cd server
    - npm install
    - npm run build
    - ls
    - echo "Backend application has been built successfully."
  artifacts:
    when: on_success
    paths:
      - prod

frontend-build:
  stage: build
  tags:
    - dalfcs_docker_autoscale
  image: node:latest
  script:
    - ls
    - echo "Started building backend application."
    - cd FrontEnd
    - npm install
    - npm run build
    - echo "Backend application has been built successfully."
  artifacts:
    when: on_success
    paths:
      - FrontEnd/dist


backend-test:
  stage: test
  tags:
    - dalfcs_docker_autoscale
  image: node:latest
  script:
    - ls
    - echo "Backend application test started."
    - cd server
    - npm run test
    - echo "Backend application Tested successfully."
  artifacts:
    when: on_success
    paths:
      - server/prod

backend-publish-deploy:
  stage: deploy
  image: node:latest
  tags:
    - dalfcs_docker_autoscale
  before_script:
    - apt-get update && apt-get install -y zip
    - apt-get install -y sshpass
  script:
    - ls
    - cd server
    - chmod og-rwx ${VM_PRIVATE_KEY}
    - cd ../
    - zip -r server.zip server
    - ls
    - sshpass -V    
    - export SSHPASS=${VM_PASS}
    - sshpass -e scp -o StrictHostKeyChecking=no server.zip "csci5308vm5@csci5308vm5.research.cs.dal.ca:"
    - sshpass -e ssh csci5308vm5@csci5308vm5.research.cs.dal.ca "sh ./start_backend.sh"
  only:
    refs:
      - deployment


frontend-publish-deploy:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y zip
    - apt-get install -y sshpass
  tags:
    - dalfcs_docker_autoscale
  script:
    - ls
    - cd FrontEnd
    - cd dist
    - chmod og-rwx ${VM_PRIVATE_KEY}
    - sshpass -V    
    - export SSHPASS=${VM_PASS}
    - sshpass -e scp -o StrictHostKeyChecking=no FrontEnd.zip "csci5308vm5@csci5308vm5.research.cs.dal.ca:"
    - sshpass -e ssh csci5308vm5@csci5308vm5.research.cs.dal.ca "sh ./start_frontend.sh" 
  dependencies:
    - frontend-build
  only:
    refs:
      - deployment
